package:
    name: libxc
    version: {{ PROJECT_VERSION }}
source:
    fn: libxc-3.0.0.tar.gz
    url: http://www.tddft.org/programs/octopus/down.php?file=libxc/libxc-3.0.0.tar.gz
    sha256: 5542b99042c09b2925f2e3700d769cda4fb411b476d446c833ea28c6bfa8792a
build:
    number: 0 
requirements:
    build:
      - {{ compiler('c') }}
      - {{ compiler('cxx') }}
      - {{ compiler('fortran') }}
      - ccache
    host: []
    run: []
about:
    home: http://www.tddft.org/programs/libxc/
    license: MPL 2.0
    summary: Libxc is a library of exchange-correlation functionals for density-functional theory. 
